[package]
name = "rust-guide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_guide"
path = "src/lib.rs"

[dependencies]
humantime = "2.1.0"
chrono = "0.4.24"
